language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t joanmelo85/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true joanmelo85/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "sa-east-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-sa-east-1-616658420430"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "AWS_SECRET_KEY"